CREATE TABLE [dbo].[FactTransacciones] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [TipoTransaccion_Id]    INT             NOT NULL,
    [Date_Id]               INT             NOT NULL,
    [Producto_Id]           INT             NOT NULL,
    [Proveedor_Id]          INT             NULL,
    [Cliente_Id]            INT             NULL,
    [Vendedor_Id]           INT             NULL,
    [Supervisor_Id]         INT             NULL,
    [Segmanto_Id]           INT             NULL,
    [Rubro_Id]              INT             NULL,
    [GruposEstacionales_Id] INT             NULL,
    [GruposNegocios_Id]     INT             NULL,
    [Cantidad_KG]           DECIMAL (18, 4) NULL,
    [Cantidad_BU]           DECIMAL (18, 4) NULL,
    [Cantidad_LTS]          DECIMAL (18, 4) NULL,
    [Importe]               DECIMAL (18, 4) NULL,
    [Numero_Factura]        VARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([Cliente_Id]) REFERENCES [dbo].[DimClientes] ([Id]),
    FOREIGN KEY ([Date_Id]) REFERENCES [dbo].[DimDate] ([Id]),
    FOREIGN KEY ([GruposEstacionales_Id]) REFERENCES [dbo].[DimGruposEstacionales] ([Id]),
    FOREIGN KEY ([GruposNegocios_Id]) REFERENCES [dbo].[DimGruposNegocios] ([Id]),
    FOREIGN KEY ([Producto_Id]) REFERENCES [dbo].[DimProductos] ([Id]),
    FOREIGN KEY ([Proveedor_Id]) REFERENCES [dbo].[DimProveedores] ([Id]),
    FOREIGN KEY ([Rubro_Id]) REFERENCES [dbo].[DimRubros] ([Id]),
    FOREIGN KEY ([Segmanto_Id]) REFERENCES [dbo].[DimSegmentos] ([Id]),
    FOREIGN KEY ([Supervisor_Id]) REFERENCES [dbo].[DimSupervisores] ([Id]),
    FOREIGN KEY ([TipoTransaccion_Id]) REFERENCES [dbo].[DimTiposTransacciones] ([Id]),
    FOREIGN KEY ([Vendedor_Id]) REFERENCES [dbo].[DimVendedores] ([Id])
);

